### ISSUE TITLE
The requested URL returned error: 403

### ISSUE THREAD

**Issue by anonymous-leviathan** [anonymous-leviathan/react-app-deployment-github-pages-via-github-actions#1]
following errors occurred
- The requested URL returned error: 403
- Process Error: remote: Permission

![{ADCC4E2C-05E7-41D3-8312-197259E463B8}](https://github.com/user-attachments/assets/951318ea-a7bd-45ea-9068-183382bfcc37)

- repo link
```bash
https://github.com/anonymous-leviathan/react-app-deployment-github-pages-via-github-actions.git
```
- .yml
```yml
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy with gh-pages
        run: |
           git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
           npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

- json file
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "homepage": "https://anonymous-leviathan.github.io/my-app",
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "deploy": "gh-pages -d build",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "gh-pages": "^6.2.0"
  }
}
```
help me to fix this
